### ISSUE TITLE
IBC Transfer action causing JS Error

### ISSUE THREAD

**Issue by dimiandre** [DA0-DA0/dao-dao-ui#1755]
When I press publish with an IBC Transfer action i get this

<img width="1731" alt="Screenshot 2024-03-11 alle 09 29 15" src="https://github.com/DA0-DA0/dao-dao-ui/assets/543292/cc6d431f-67a4-4995-bda7-8e711a4fa3ab">

action:

<img width="993" alt="Screenshot 2024-03-11 alle 09 31 19" src="https://github.com/DA0-DA0/dao-dao-ui/assets/543292/f0962bd2-9714-411a-92a3-4a8f97364039">

console
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.transform (index.tsx:733:47)
    at actions.ts:51:29
    at Array.map (<anonymous>)
    ```

**Comment by dimiandre** [comment]
it works now! thanks @NoahSaso
